### ISSUE TITLE
Thu thập dữ liệu thương mại điện tử

### ISSUE THREAD

**Issue by hawkin-dono** [hawkin-dono/Ecommerce-website#7]
- Tìm dữ liệu về sản phẩm của các sàn thương mại điện tử: amazon, shopee, lazada,…. (Hoặc có thể là các trang web bán hàng như thế giới di động,…)
- Yêu cầu về data:
    - Có ảnh
    - Có mô tả
    - Có loại sản phẩm
    - Có chứa đánh giá của người dùng về sản phẩm

**Comment by thelong9** [comment]
[comments_data_dien_gia_dung.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036879/comments_data_dien_gia_dung.csv)
[comments_data_dien_thoai_may_tinh_bang.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036880/comments_data_dien_thoai_may_tinh_bang.csv)
[comments_data_do_choi_me_be.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036881/comments_data_do_choi_me_be.csv)
[comments_data_lam_dep_suc_khoe.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036882/comments_data_lam_dep_suc_khoe.csv)
[comments_data_nha_cua_doi_song.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036883/comments_data_nha_cua_doi_song.csv)
[comments_data_o_to_xe_may_xe_dap.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036884/comments_data_o_to_xe_may_xe_dap.csv)
[comments_data_the_thao_da_ngoai.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036886/comments_data_the_thao_da_ngoai.csv)
[comments_data_thiet_bi_kts_phu_kien_so.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036887/comments_data_thiet_bi_kts_phu_kien_so.csv)
[comments_data_thoi_trang_nu.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036888/comments_data_thoi_trang_nu.csv)
[comments_data_bach_hoa_online.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036889/comments_data_bach_hoa_online.csv)

data về comment

**Comment by thelong9** [comment]
[crawled_data_lam_dep_suc_khoe.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036900/crawled_data_lam_dep_suc_khoe.csv)
[crawled_data_nha_cua_doi_song.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036901/crawled_data_nha_cua_doi_song.csv)
[crawled_data_o_to_xe_may_xe_dap.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036903/crawled_data_o_to_xe_may_xe_dap.csv)
[crawled_data_the_thao_da_ngoai.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036904/crawled_data_the_thao_da_ngoai.csv)
[crawled_data_thiet_bi_kts_phu_kien_so.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036905/crawled_data_thiet_bi_kts_phu_kien_so.csv)
[crawled_data_thoi_trang_nu.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036906/crawled_data_thoi_trang_nu.csv)
[crawled_data_bach_hoa_online.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036907/crawled_data_bach_hoa_online.csv)
[crawled_data_dien_gia_dung.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036908/crawled_data_dien_gia_dung.csv)
[crawled_data_dien_thoai_may_tinh_bang.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036909/crawled_data_dien_thoai_may_tinh_bang.csv)
[crawled_data_do_choi_me_be.csv](https://github.com/hawkin-dono/Ecommerce-website/files/15036911/crawled_data_do_choi_me_be.csv)


data về product

**Comment by thelong9** [comment]
[E- commerce website.zip](https://github.com/hawkin-dono/Ecommerce-website/files/15051152/E-.commerce.website.zip)
